### ISSUE TITLE
ヒエラルキーのコンポーネントの命名規則を作って修正する

### ISSUE THREAD

**Issue by sgmtsnj** [kyo-waku/SiriBal#17]
ヒエラルキーのコンポーネントが増えてきたので、UI系、ゲームマネージャー系、サーバー通信系、みたいに分けて、Prefixつけて分かりやすくしたい

**Comment by yamamotoshuhei888** [comment]
これ、しんちゃんがやってくれたし、closeにしちゃっていいんじゃない？

**Comment by sgmtsnj** [comment]
だいたい終わったよね
