### ISSUE TITLE
光源の位置がよくない？バルーンを置くと裏側が真っ黒になる。

### ISSUE THREAD

**Issue by sgmtsnj** [kyo-waku/SiriBal#28]

**Comment by sgmtsnj** [comment]
光は上の方から当てるようにしておく
ARとして影を描画できたらベター
平面検出して描けないかなぁ

**Comment by yamamotoshuhei888** [comment]
モデルにライティングの設定があるんだけど、それが正しく読み込めていないことまでは理解したんだけど、それをどうやってモデルに反映させるのかが分かってない。

**Comment by 5104** [comment]
確認したところ、バルーンの3Dモデル自体に影はなさそう。
光源の逆側が暗いのは環境光の設定で解決できそう。
AR画面での調整は来週実機で確認させてください〜

以下、参考
http://nn-hokuson.hatenablog.com/entry/2016/11/01/205056
http://bluebirdofoz.hatenablog.com/entry/2018/07/08/221919

**Comment by sgmtsnj** [comment]
ほー、ありがとう！！環境光ってのがあるのかぁ
