### ISSUE TITLE
追加した各ウェポンの獲得ゲーム側のクリア条件を考える

### ISSUE THREAD

**Issue by sgmtsnj** [kyo-waku/SiriBal#51]
コーラの缶
靴
ハンマー
を考える。みんなで考えよう。

ちなみにストーンは目の前に出る3つのバルーンをストーン3つでミスなく落とせばok

**Comment by sgmtsnj** [comment]
https://kyo-waku.slack.com/archives/CMVKU4G3Z/p1584524228008600

このスレッドで盛り上がっているので、記録用リンク

**Comment by sgmtsnj** [comment]
5104のアイディア

・スコアXX点以上達成したらコーラ缶獲得
・ランクXXまで到達したら靴獲得
・XXの武器を使ってバルーンをXX個割ったら…
・1つの投擲で3つバルーンを当てたら…
・バルーンの攻撃を一度も食らわずにXXしたら…
・どこかにある隠しボタンタップしたらKYO-wakuさん獲得

**Comment by yamamotoshuhei888** [comment]
連射性能を消費MP量みたいな形の代用で実装するのもありだよね
