### ISSUE TITLE
RaycastMaskのバグを直す

### ISSUE THREAD

**Issue by yamamotoshuhei888** [kyo-waku/SiriBal#54]

**Comment by yamamotoshuhei888** [comment]
Iconの設定、2D-Spriteを設定した後にAdvancedのRead/Write Enabbledにチェックが必要だったわ
<img width="285" alt="スクリーンショット 2020-03-18 23 07 20" src="https://user-images.githubusercontent.com/52473459/76969354-9deb0b80-696d-11ea-9e6c-31fbce45b73f.png">

**Comment by sgmtsnj** [comment]
ほー！！
なんかこういうテクニカルな情報溜め込みたいなー
やっぱnoteかなー

**Comment by yamamotoshuhei888** [comment]
テクニカル情報はQiitaが多い印象がありますなー
