### ISSUE TITLE
AppStoreに書くプロモーションテキストと概要説明の文章を考える

### ISSUE THREAD

**Issue by sgmtsnj** [kyo-waku/SiriBal#75]

**Comment by yamamotoshuhei888** [comment]
メモ：
・プロモーションテキスト：AppStoreでスクショのすぐあとに出る奴。
・概要説明：提出用（真面目に）；日本語で良い。

＜しんじさん要望＞
・おちゃめなプロモーションテキストが良い。

**Comment by yamamotoshuhei888** [comment]
概要説明：
・AR空間に浮かべたバルーンを次々に撃ち落とす爽快なゲームです。

プロモーションテキスト：
・ハルキ風？：

「やれやれ」
僕はスマートフォンのガラス面に浮かぶバルーンを眺めて、首を振った。
「これはつまり、この気球を撃ち落とせばいいってことかい？」
「そうだよ、君は、石や靴を投げて、気球を撃ち落とせばいい。君の望む通りにね」
「僕の望む通りに…」
「ああ」
彼は頷いた。まるで未来を知る預言者のように、鷹揚に。
「僕が君のベストスコアを超えたら、今日の夕食は君の奢り、そういうことだったね？」
「そうだよ」
彼は少しも淀みなく言った。
「OK、じゃあ、始めようか」
僕は薄いガラス面をタップする。
軽快な音楽ととともに、仮想の気球が空を舞い始めた。

**Comment by sgmtsnj** [comment]
好きすぎる

**Comment by yamamotoshuhei888** [comment]
プロモーションテキスト２：GlobalElite風

ソーシャルディスタンス！（時候の挨拶）

世は猫も杓子もコロナウィルスである。
自粛生活を楽しんでいるだろうか？　在宅勤務には慣れただろうか？
とはいえいい加減家の中に閉じこもっている生活にも懲り懲りだという人もいるのではないか。
なにせ運動ができない。
ランニングするのにマスクは辛いし、近所を散歩するにも限界がある。
リングでフィットなアドベンチャーもあるという噂だが、品薄ですっかり手に入らない。
そう、我々は今や砂漠の中にいるのだ。水分の代わりに運動習慣を奪われた。

ところでこのアプリは気球を落とすゲームだ。
ゲームを起動すれば、あなたの部屋に無数の気球が現れる。
石や靴やハンマーを投げて気球を打ち落とすと、得点をゲットできる。
いささか単純なゲームだ。
ところがこの気球、攻撃してくる。攻撃されるので、あなたは避けなければならない。
携帯を持って。
すなわち、動ける。
ちょっとした運動になると思う。

単純なゲームだから、お子様も楽しめるだろう。
そして、素晴らしいことにこのゲームは無料だ。
コロナウィルスで暇を持て余した我々は無料でゲームを作る。
砂漠のオアシスにならなくても、このアプリがあなたのコップ一杯の水になれば嬉しい。

**Comment by sgmtsnj** [comment]
COVID-19ネタはリジェクトされたので、はるき風で2回目チャレンジする

**Comment by yamamotoshuhei888** [comment]
Closeします！

**Comment by yamamotoshuhei888** [comment]
リリース一旦したのでCloseしますね
